spring.application.name=TechCodesolution
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/stud}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Aman#098}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${SERVER_PORT:8082}

app.jwtSecret=${JWT_SECRET:YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OQ==}
app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=${UPLOAD_DIR:uploads/roadmaps}

# Email Properties (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amanraj3704@gmail.com
spring.mail.password=rfkmibfsqfleyxmh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Judge0 integration
#judge0.api.url=${JUDGE0_API_URL:http://localhost:2358}

# JDoodle integration (uncomment and fill these values to enable JDoodle)
jdoodle.client.id=${JDOODLE_CLIENT_ID:4ca6cd0d1602a448586a7051fd957ec6}
jdoodle.client.secret=${JDOODLE_CLIENT_SECRET:a195f7ec471f2e583be50764ee4a7ad78da89bad1c6aabdeecfdaec485bbbae0}

#4ca6cd0d1602a448586a7051fd957ec6
#a195f7ec471f2e583be50764ee4a7ad78da89bad1c6aabdeecfdaec485bbbae0
